<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>PingNotify.Android</RootNamespace>
    <ApplicationTitle>PingNotify</ApplicationTitle>
    <ApplicationId>com.willeastbury.pingnotify</ApplicationId>
    <SupportedOSPlatformVersion>26.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>
  </PropertyGroup>
</Project>
