<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>PingNotify</AssemblyName>
    <RootNamespace>PingNotify</RootNamespace>
    <Version>0.0.8</Version>
    <AssemblyVersion>0.0.8.0</AssemblyVersion>
    <FileVersion>0.0.8.0</FileVersion>
    <WindowsSdkPackageVersion>10.0.26100.87</WindowsSdkPackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UIAutomationClient">
      <HintPath>$(ProgramFiles)\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.11\ref\net10.0\UIAutomationClient.dll</HintPath>
    </Reference>
    <Reference Include="UIAutomationTypes">
      <HintPath>$(ProgramFiles)\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\10.0.11\ref\net10.0\UIAutomationTypes.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
